version: "3"

services:
  node-app:
    image: aluku/image:blog #  Replace with your Docker Hub image details
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    ports:
      - 3000:3000

  nginx-app:
    image: aluku/image:blogReplace with your Docker Hub image details
    ports:
      - 80:80
      - 443:443
    depends_on:
      - node-app
    volumes:
      - ./certbot/conf:/etc/nginx/conf.d
      - ./certbot/certs:/etc/nginx/certs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/certs:/etc/nginx/certs
    command: certonly --webroot --webroot-path=/etc/letsencrypt --email your-email@example.com --agree-tos --no-eff-email --staging -d alukublog.com # Replace with your email and domain
    depends_on:
      - nginx-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
