version: "3.8"

services:
  node-app:
    image: aluku/image:blog # Replace with your Docker Hub image details
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    ports:
      - 3000:3000
    networks:
      - app-network

  nginx-app:
    image: aluku/image:blognginx # Replace with your Docker Hub image details
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    ports:
      - 80:80
      - 443:443
    depends_on:
      - node-app
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/certs:/etc/nginx/certs
    command: certonly --webroot --webroot-path=/etc/letsencrypt --email foreveraluku@gmail.com --agree-tos --no-eff-email --staging -d alukublog.com # Replace with your email and domain
    depends_on:
      - nginx-app
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
