version: "3.8"

services:
  blog:
    image: aluku/image:blog
    ports:
      - "3000:3000"
    deploy:
      replicas: 8
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
