version: "3.8"

services:
  nextjs:
    image: aluku/image:blog
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
