# Base image
FROM nginx

# Install Certbot
RUN apt-get update && \
    apt-get install -y certbot

# Expose HTTP and HTTPS ports
EXPOSE 80 443

# Copy NGINX configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Start NGINX service
CMD ["nginx", "-g", "daemon off;"]
